apiVersion: mcad.ibm.com/v1alpha1
kind: AppWrapper
metadata:
  name: stateful-set-2-replicas
  labels: 
    TestTree: "C"
spec:
  schedSpec:
    minAvailable: 2
  resources:
    Items:
    - replicas: 1
      type: StatefulSet
      template:
        apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
        kind: StatefulSet
        metadata:
          name: stateful-set-2-replicas
          labels:
            app: stateful-set-2-replicas
        spec:
          selector:
            matchLabels:
              app: stateful-set-2-replicas
          replicas: 2
          template:
            metadata:
              labels:
                app: stateful-set-2-replicas
                size: "2"
            spec:
              containers:
               - name: stateful-set-2-replicas
                 image: k8s.gcr.io/echoserver:1.4
                 resources:
                   requests:
                     cpu: "0.1"
                     memory: "200Mi"
                   limits:
                     cpu: "0.1"
                     memory: "200Mi"
