apiVersion: mcad.ibm.com/v1alpha1
kind: AppWrapper
metadata:
  labels:
  name: aw-pi
  namespace: default
spec:
  schedulingSpec:
    clusterScheduling:
      clusters:
      - name: cluster3
  resources:
    GenericItems:
    - replicas: 1
      generictemplate:
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: pi
        spec:
          template:
            spec:
              containers:
              - name: pi
                image: perl
                command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
              restartPolicy: Never
          backoffLimit: 4
