#{{ if .Values.configMap.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: kube-system
data:
  QUOTA_ENABLED: {{ .Values.configMap.quotaEnabled }}
  DISPATCHER_MODE: {{ .Values.configMap.dispatcherMode }}
  DISPATCHER_AGENT_CONFIGS: {{ .Values.configMap.agentConfigs }}
  QUOTA_REST_URL: {{ .Values.configMap.quotaRestUrl }}
#{{ end }}
